### ISSUE TITLE
golibmc flush

### ISSUE THREAD

**Issue by dears** [douban/libmc#100]
Hi,  
Thank you for the wonderful package.   
We use golibmc.   
Is there a good way to flush all the data in memcached?  

Thanks.

**Comment by mckelvin** [comment]
Hey @dears , I guess [the flush_all command](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L1111) has never been implemented in the libmc. I don't think it's reasonable for an application to flush cache servers. Could you please let us know what's your original requirements ?

If you just want to do this for OPS purpose, I'd suggest doing this in shell:

```bash
$ echo -ne "flush_all\r\n" | nc 127.0.0.1 11211
OK
```

**Comment by dears** [comment]
Thank you for your quick reply.

I wanted to use this library from the operation management system if possible.
Since it is implemented in other libraries (e.g.: gomemcache, pylibmc), I was looking for a good way with golibmc.

**Comment by mckelvin** [comment]
Hey @dears , I'm going to label this issue as a feature request as it's not implemented yet. Anyone is welcome to implement this feature. I can't promise when the feature will be ready but I'll have a look at it during the weekend.

**Comment by dears** [comment]
Hi @mckelvin ,
Thank you very much for your prompt response. very helpful. 
We are looking forward to it.

**Comment by mckelvin** [comment]
@dears Can you try https://github.com/douban/libmc/pull/101 ?

**Comment by dears** [comment]
Our tests were working fine and there was no problem. 
Thank you very much for the implementation!

**Comment by mckelvin** [comment]
@dears Good to know!

FYI: As discussed in #101, we have some concerns about this feature since it's too powerful. Finally we decide to disable this feature by default. To enable this feature, you need to call `mc.ToggleFlushAllFeature(True)` once before calling the `mc.FlushAll()`.

**Comment by dears** [comment]
Hi, @mckelvin .

Although it was able to execute when executed before the other day the ToggleFlushAllFeature is implemented (`v1.2.2-0.20190727161116-0cf445565490`), execution will cause an error on the latest branch(`v1.2.2-0.20190801073747-5ccc40c13eb7`).

error :` libmc: network error(programming_error).`

Do you understand the cause?

**Comment by mckelvin** [comment]
@dears That's on purpose. Please see my previous comment.

**Comment by dears** [comment]
@mckelvin 
I am sorry that I have not enough words. 
ToggleFlushAllFeature(true) is calling. 
Probably because it did not set data. 

If no data is set, is it a specification that returns an error?

**Comment by mckelvin** [comment]
@dears 
The `ToggleFlushAllFeature` is used to enable(true) and disable(false) the `flush_all` feature.
The feature is disabled by default as flush all is a dangerous action. When it's disabled, a programming error will be raised to avoid dangerous action. You can see https://github.com/douban/libmc/blob/master/src/golibmc_test.go#L918-L961 for details.

Does that make sense?

**Comment by dears** [comment]
@mckelvin 
Sorry for my poor explanation.
In this test case, SetMulti is performed and then FlushAll is performed. 
Even if ToggleFlushAllFeature is enabled, 
an error will occur if FlushAll is performed without performing Set.

error  
libmc: network error(programming_error)  
 ``` 
func main() {
	client := golibmc.New([]string{"localhost:21252", "localhost:21253"},
                                      false, "local:", 
                                      golibmc.HashCRC32, true, false)

	client.ToggleFlushAllFeature(true)
	_, err := client.FlushAll()
	if err != nil {
		fmt.Println(err)
	}
} 
```

non error
```
func main() {
	client := golibmc.New([]string{"localhost:21252", "localhost:21253"},
                                      false, "local:", 
                                      golibmc.HashCRC32, true, false)
	// Set
	client.Set(&golibmc.Item{
		Key:   "test",
		Value: []byte("value"),
	})

	client.ToggleFlushAllFeature(true)
	_, err := client.FlushAll()
	if err != nil {
		fmt.Println(err)
	}
} 
```

**Comment by mckelvin** [comment]
Hey @dears , I gotcha now. That's a bug. The programming_error is raised because `ToggleFlushAllFeature` is not called successfully. When it's called, no connection is established yet. I'll fix it later. Only the golang version is affected. You can keep the workaround for now until it's fixed.

**Comment by mckelvin** [comment]
@dears Could you please review https://github.com/douban/libmc/pull/104/files  ?
