### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [douban/libmc#102]
https://github.com/douban/libmc/blob/5560a82e0f24a50d2203082181ac1d3860d17d4e/src/BufferReader.cpp#L462

在462行使用new进行内存分配，但在468行return时，没有进行释放

**Comment by mckelvin** [comment]
感谢报告问题。乍一看我也以为我写出内存泄漏valgrind都没检查出来。仔细阅读了代码后我发现这个地方理论上有泄漏，实际上没有泄漏。

`parseTokenData` 这个函数比较特殊，在处理网络包的过程中，当一个包过大时，可能是通过2+次 `recv` 这一系统调用完成的，在返回给应用层时，应用层可不希望这个地方的数据是由多块分散的内存组成的，所以这个有了462行的这个内存拷贝。但还有些时候，返回的包尺寸比较小，全是1次 recv 就搞定了，这样就没必要内存复制。这样一来 parseTokenData 返回的内存指针有时候需要释放，有时候不需要释放。

parseTokenData 会在几处被调用：1) 处理 `get` 的返回结果，2) 复制 3) 处理 error, server_error, client_error (message). 预期只有1, 2 有可能分成了2+份，需要释放内存，代码里已经做了释放。其他几种情况都是几十个字节以内的数据，基本没可能拆除多份。

为了保险期间我准备让所有地方都判断下是否有必要释放内存。

再次感谢报告问题。
