### ISSUE TITLE
Got RuntimeError when use flush_all in Python3.7

### ISSUE THREAD

**Issue by Leosocy** [douban/libmc#105]
RuntimeError: Please call toggle_flush_all_feature(true) first to enable the flush_all feature.

**Comment by mckelvin** [comment]
Hey there, that's by design. By calling the flush_all command, all data in all memcached instances will be cleaned up, which is dangerous. We decide to disable the feature by default. So if you need to use it, please follow the advice and call client.toggle_flush_all_feature(True) ahead.

**Comment by Leosocy** [comment]
emmmmm. I think the error message is not easily understand, if it say `Please call client.toggle_flush_all_feature(true) ...` then I know how to resolve.

**Comment by mckelvin** [comment]
Good idea. To be resolved in #106 .
