### ISSUE TITLE
[Question] Failover time lags and timeout setting

### ISSUE THREAD

**Issue by dears** [douban/libmc#111]
Hi,
Thanks for a good library.

We are currently testing the connection of Elasticache memcache from golibmc,
When config failover = true, dropping the node and reconnecting will result in a time lag of about 10 to 15 minutes from when the node starts up to when it comes back to access.

I tried to change RetryTimeout, ConnnectTimeout, Polltimeout, but it didn't improve.

Reading the reference how each Timeout works, I was not sure,
Could you tell us the cause of this time lag and the role of the above three Timeouts?

**Comment by mckelvin** [comment]
Hi @dears ,

The failover logic is in 
https://github.com/douban/libmc/blob/3ea9431acebe0cf37bd8bb092acad8116c22a1d9/src/HashkitKetama.cpp#L125-L138 , as you can see, the client will try to [reuse the failed node after every `m_retryTimeout`(default=MC_DEFAULT_RETRY_TIMEOUT=5) 
 seconds](https://github.com/douban/libmc/blob/3ea9431acebe0cf37bd8bb092acad8116c22a1d9/src/Connection.cpp#L176). There's no such thing like background jobs to do the reconnect, you have to touch(get, set, ...) the node to trigger the reconnection.
There's a test case to make sure the reconnect delay is working correctly. It's written in Python https://github.com/douban/libmc/blob/master/tests/shabby/reconnect_delay.py .

I don't know the detail of your setup but here are something I can think of:

1. Uncomment [this line](https://github.com/douban/libmc/blob/3ea9431acebe0cf37bd8bb092acad8116c22a1d9/src/Connection.cpp#L185) to see if the connection checker is running after every X seconds.
2. Make sure the value of RetryTimeout in golang is successfully assigned to douban::mc::Connection::m_retryTimeout. The unit should be `second`.
3. Is there anything like proxy between the client and the Elasticache? Is that working correctly?
4. Try to minimize the issue and write a MWE(minimal working example) so we can reproduce and help you debug this issue.

Hopefully this helps.
