### ISSUE TITLE
libmc出现 libmc._client.ThreadUnsafe的报错信息

### ISSUE THREAD

**Issue by Adhders** [douban/libmc#113]
我使用libmc出现了下面的问题
libmc._client.ThreadUnsafe: mc client created in (2= 6551, 'Thread-2') [<FrameSummary file /opt/chche/app_with_mc.py, line 6 in <module>&= gt;, <FrameSummary file <frozen importlib._bootstrap>, line 971 in=_find_and_load>, <FrameSummary file <frozen importlib._bootstrap&= gt;, line 955 in _find_and_load_unlocked>, <FrameSummary file <fro= zen importlib._bootstrap>, line 665 in _load_unlocked>, <FrameSumm= ary file <frozen importlib._bootstrap_external>, line 678 in exec_mod= ule>, <FrameSummary file <frozen importlib._bootstrap>, line 21= 9 in _call_with_frames_removed>, <FrameSummary file /opt/chche/mc.py,=line 18 in <module>>], called in (26551, 'Thread-27')

我把Memcached 的client改为pylibmc,其它代码不改动就没这个问题，我的libmc是这么配置的
`
mc = Client(
    [
        'localhost',
    ],
    do_split=True,
    comp_threshold=0,
    noreply=False,
    prefix=None,
    hash_fn=MC_HASH_MD5,
    failover=False
)

mc.config(MC_POLL_TIMEOUT, 100)  # 100 ms
mc.config(MC_CONNECT_TIMEOUT, 300)  # 300 ms
mc.config(MC_RETRY_TIMEOUT, 5)  # 5 s
`

**Comment by mckelvin** [comment]
Hi, 这是因为单个客户端并不是线程安全的。当一个客户端实例在一个线程中创建，在另一个使用时libmc会主动抛出这个错误提示用户。
pylibmc 也是一样的，只是没有主动抛出错误。pylibmc 在 https://github.com/lericson/pylibmc/blob/849c682f925f57119b1813f90c27ab9335953c2e/src/pylibmc/pools.py#L19-L20 中有提及单个客户端不是线程安全的。

不管使用哪一种客户端，如果在多线程下使用的话建议在上层包一层线程池(比如 pylibmc 里这个 pools.py 里的实现)，或者一个线程一个客户端(可以用 [threading.local](https://docs.python.org/2/library/threading.html#threading.local))。如果你本意并非在多线程环境中使用libmc, 你可以考虑惰性实例化libmc客户端，在某个线程中需要客户端的时候再实例化，这样就不会在主线程中被实例化了。

**Comment by Adhders** [comment]
mckelvin ，你好, 我程序里没有使用多线程，只开了一个服务，我看官网说libmc is a single-threaded memcached client，那为何还会出现单个客户端并不是线程安全的。请问python如何惰性实例化libmc客户端呀，下面是我目前的mc.py
`
from libmc import (
    Client, MC_HASH_MD5, MC_POLL_TIMEOUT, MC_CONNECT_TIMEOUT, MC_RETRY_TIMEOUT
)
mc = Client(
    [
        'localhost',
        'localhost:11212',
    ],
    do_split=True,
    comp_threshold=0,
    noreply=False,
    prefix=None,
    hash_fn=MC_HASH_MD5,
    failover=False
)

mc.config(MC_POLL_TIMEOUT, 100)  # 100 ms
mc.config(MC_CONNECT_TIMEOUT, 300)  # 300 ms
mc.config(MC_RETRY_TIMEOUT, 5)  # 5 s

`

**Comment by Adhders** [comment]
> do_split=True,
> comp_threshold=0,
> noreply=False,
> prefix=None,
> hash_fn=MC_HASH_MD5,
> failover=False
> )
> 
> mc.config(MC_POLL_TIMEOUT, 100) # 100 ms
> mc.config(MC_CONNECT_TIMEOUT, 300) # 300 ms
> mc.config(MC_RETRY_TIMEOUT, 5) # 5 s
> 
> `


> Hi, 这是因为单个客户端并不是线程安全的。当一个客户端实例在一个线程中创建，在另一个使用时libmc会主动抛出这个错误提示用户。
> pylibmc 也是一样的，只是没有主动抛出错误。pylibmc 在 https://github.com/lericson/pylibmc/blob/849c682f925f57119b1813f90c27ab9335953c2e/src/pylibmc/pools.py#L19-L20 中有提及单个客户端不是线程安全的。
> 
> 不管使用哪一种客户端，如果在多线程下使用的话建议在上层包一层线程池(比如 pylibmc 里这个 pools.py 里的实现)，或者一个线程一个客户端(可以用 [threading.local](https://docs.python.org/2/library/threading.html#threading.local))。如果你本意并非在多线程环境中使用libmc, 你可以考虑惰性实例化libmc客户端，在某个线程中需要客户端的时候再实例化，这样就不会在主线程中被实例化了。

我mc用在了flask web程序里，虽然我没有使用多线程，但是flask内部有多线程，可能这个导致了mc报错

**Comment by mckelvin** [comment]
> flask内部有多线程，可能这个导致了mc报错

对的。是这个原因。惰性实例化可以参考 https://en.wikipedia.org/wiki/Lazy_initialization#Python
