### ISSUE TITLE
failover befavior seems strange

### ISSUE THREAD

**Issue by mosasiru** [douban/libmc#46]
I have two trouble using `failover` feature.

First, this is not a problem but just a confusing, libmc occurs error when `failover`  is true and there is just one memcached server.

## example1
```go
package main

import (
	"log"

	"github.com/douban/libmc/golibmc"
)

func main() {
	servers := []string{
		"localhost:11211 local111",
	}
	noreply := false
	prefix := ""
	hashFunc := golibmc.HashMD5
	failover := true
	disableLock := false
	c := golibmc.New(
		servers, noreply, prefix, hashFunc,
		failover, disableLock,
	)
	val, err := c.Get("key")
	if err != nil {
		log.Printf("err: %s", err)
		return
	}
	log.Printf("val: %s", val.Value)

}

```
it results 
```
err: libmc: network error(server_error)
```

it doesn't occur when there are more than two servers, or `failover: false`.

Second, when servers are two and `failover: true`,  only the one memcached is used.

## example2

In advance,  I ran two memcached with each other port.

```
memcached -p 11211 -vvv
memcached -p 11212 -vvv
```

then run below code.
It call 1000 times Set and Get memcached with each other keys.

```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/douban/libmc/golibmc"
)

func main() {
	servers := []string{
		"localhost:11211 local111",
		"localhost:11212 local112",
	}
	noreply := false
	prefix := ""
	hashFunc := golibmc.HashMD5
	failover := true
	disableLock := false
	c := golibmc.New(
		servers, noreply, prefix, hashFunc,
		failover, disableLock,
	)
	for i := 1; i <= 1000; i++ {
		time.Sleep(100 * time.Millisecond)
		key := fmt.Sprintf("key%d", i)
		err := c.Set(&golibmc.Item{Key: key, Value: []byte("value"), Expiration: 10})
		if err != nil {
			log.Printf("key: %s, set err: %s", key, err)
			continue
		}
		val, err := c.Get(key)
		if err != nil {
			log.Printf("key: %s, get err: %s", key, err)
			continue
		}
		log.Printf("key: %s, val: %s", key, val.Value)
	}

}
```

It seems that only one memcached is used. 

(I read   https://github.com/douban/libmc/wiki/Features#auto-failover, although my environment is distributed, but I decide to use this feature because I prefer fault-tolerance to consistency)

**Comment by mckelvin** [comment]
@mosasiru Thanks for reporting! The issue can be reproduced and confirmed. The `failover = true` behaviour is not used in Douban's production environment and is not well tested.

I'll fix and detail more about the bug in following PR.

**Comment by mosasiru** [comment]
@mckelvin I see! I'll continue to test this feature in my development environment. Thank you.

**Comment by mckelvin** [comment]
@mosasiru Would you please try #48 or import module from `"github.com/mckelvin/libmc/golibmc"`. Sorry about the bug. I wish you would keep on using libmc. The failover=true behaviour is not fully tested and may still have some bugs. Please let me know if there'e anything unexpected.

**Comment by mosasiru** [comment]
@mckelvin I made sure that your branch fixed this issue! Thank you very much! 
I'll keep using this module because of great features and kindful supports  :)

**Comment by windreamer** [comment]
@youngsofun @MOON-CLJ pls review
