### ISSUE TITLE
golibmc connects memcached via unix domain socket.

### ISSUE THREAD

**Issue by ikeikeikeike** [douban/libmc#49]
Hi there :)
Just I ask that below.

I have connected to memcached via unix domain socket using Golang. Although I haven't figured out that I've got error result, which's not able to open memcached connection. Not sure, it seems like that golibmc cannot connect with unix domain sockect in currently status.

How do I do that ?, or do you have plan that's implementation accomplished ?

**Comment by mckelvin** [comment]
Yes, libmc doesn't support unix domain socket yet. I'm afraid I'm not going to implement this feature, but PRs are welcomed if anyone would like to help.

**Comment by ikeikeikeike** [comment]
ahh I got it, thanks for your response quickly :)
