### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [douban/libmc#5]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [ConnectionPool](https://github.com/douban/libmc/blob/9ed101bcde3556adbb5a1228bcf2805ddd8e8129/src/ConnectionPool.cpp#L36 "Destructor for ConnectionPool")
* [DataBlock](https://github.com/douban/libmc/blob/9ed101bcde3556adbb5a1228bcf2805ddd8e8129/src/DataBlock.cpp#L34 "Destructor for DataBlock")

**Comment by mckelvin** [comment]
@elfring Please review #6 .

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/douban/libmc/commit/f53d1c5bd44139a4891293d2f4b259302a4f5412#diff-6b049cde08edceed2718a5acad05442eL36 "Deletion of unnecessary null pointer checks").
