### ISSUE TITLE
Customise pickler

### ISSUE THREAD

**Issue by href** [douban/libmc#76]
I'm evaluating libmc for a project and I'm wondering: is there a way for us to customise the pickler? We use [dill](https://github.com/uqfoundation/dill) instead of the builtin pickler and from what I've seen there's no way to configure that.

Did I miss something in the docs/source code?

**Comment by windreamer** [comment]
Hi, you can just pickle your data to `bytes` first, then feed it to `libmc`. and unpickle after retrieve the corresponding `bytes` using `libmc` to get back the original data.

**Comment by href** [comment]
When you say it like that it seems perfectly obvious ;)
Thanks!
