### ISSUE TITLE
pip install libmc 在windows上始终失败是怎么回事？？

### ISSUE THREAD

**Issue by ChenQiangXiao** [douban/libmc#78]
include\Export.h(61): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::key_len'
    include\Export.h(77): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::type_'
    c:\users\hadoop\appdata\local\temp\pip-install-bk5sua96\libmc\include\Common.h(3): fatal error C1083: Cannot open include file: 'sys/uio.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2****

**Comment by Yensan** [comment]
Memcached 需要编译，而 Libmc 并没有给出 已经编译的 wheel。
其实豆瓣应该编译一下的。zeroMQ 也是差不多的项目，他们就把 C核心代码编译了，python客户端安装就可用。

**Comment by mckelvin** [comment]
抱歉目前尚未支持Windows，暂时也没有适配Windows的计划。欢迎发PR做兼容支持！
