### ISSUE TITLE
Maybe need to rm syslink and refactor code case Go's new dependency manager vgo not support syslink

### ISSUE THREAD

**Issue by ariesdevil** [douban/libmc#80]
ref0: https://github.com/golang/go/issues/12953
ref1: https://github.com/golang/go/issues/24057#issuecomment-377430635

**Comment by mckelvin** [comment]
@ariesdevil It has been ~1 yr since the issue was created. Does this issue still make sense? Or do you have any follow-ups on this?

**Comment by ariesdevil** [comment]
Change import path works for me.
