### ISSUE TITLE
Projects using libmc

### ISSUE THREAD

**Issue by vusirikala** [douban/libmc#83]
For our class project, we are surveying on various client libraries for Memcached. Do you know of any projects that use libmc library to connect to Memcached?

**Comment by ushuz** [comment]
https://github.com/douban, obviously. And my company (https://github.com/xiachufang) is also using libmc.

**Comment by mckelvin** [comment]
I added a section named `Who is using` in https://github.com/douban/libmc/blob/master/README.rst#who-is-using . Please feel free to update.

I'm going to close this ticket now.
